name: Teigführung
favicon: null
layout_spectrum: 0.01584020466543734
typography_spectrum: 0.611053294269368
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5055856131948531
  lightness: 0.7198997663799673
  saturation: 0.771506653400138
  rhythmicContrast: 0.8135271370410919
purpose: []
